#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-spotless
Version  : 3.23.0
Release  : 1
URL      : https://github.com/diffplug/spotless/archive/gradle/3.23.0.tar.gz
Source0  : https://github.com/diffplug/spotless/archive/gradle/3.23.0.tar.gz
Source1  : https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-plugin-gradle/3.23.0/spotless-plugin-gradle-3.23.0.jar
Source2  : https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-plugin-gradle/3.23.0/spotless-plugin-gradle-3.23.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0
Requires: mvn-spotless-data = %{version}-%{release}
Requires: mvn-spotless-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# <img align="left" src="_images/spotless_logo.png"> Spotless: Keep your code spotless

%package data
Summary: data components for the mvn-spotless package.
Group: Data

%description data
data components for the mvn-spotless package.


%package license
Summary: license components for the mvn-spotless package.
Group: Default

%description license
license components for the mvn-spotless package.


%prep
%setup -q -n spotless-gradle-3.23.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-spotless
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spotless/LICENSE.txt
cp _ext/eclipse-base/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spotless/_ext_eclipse-base_LICENSE.txt
cp _ext/eclipse-cdt/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spotless/_ext_eclipse-cdt_LICENSE.txt
cp _ext/eclipse-groovy/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spotless/_ext_eclipse-groovy_LICENSE.txt
cp _ext/eclipse-jdt/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spotless/_ext_eclipse-jdt_LICENSE.txt
cp _ext/eclipse-wtp/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spotless/_ext_eclipse-wtp_LICENSE.txt
cp lib/src/main/java/com/diffplug/spotless/generic/LicenseHeaderStep.java %{buildroot}/usr/share/package-licenses/mvn-spotless/lib_src_main_java_com_diffplug_spotless_generic_LicenseHeaderStep.java
cp plugin-maven/src/main/java/com/diffplug/spotless/maven/generic/LicenseHeader.java %{buildroot}/usr/share/package-licenses/mvn-spotless/plugin-maven_src_main_java_com_diffplug_spotless_maven_generic_LicenseHeader.java
cp plugin-maven/src/test/java/com/diffplug/spotless/maven/generic/LicenseHeaderTest.java %{buildroot}/usr/share/package-licenses/mvn-spotless/plugin-maven_src_test_java_com_diffplug_spotless_maven_generic_LicenseHeaderTest.java
cp spotless.license %{buildroot}/usr/share/package-licenses/mvn-spotless/spotless.license
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/diffplug/spotless/spotless-plugin-gradle/3.23.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/diffplug/spotless/spotless-plugin-gradle/3.23.0/spotless-plugin-gradle-3.23.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/diffplug/spotless/spotless-plugin-gradle/3.23.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/diffplug/spotless/spotless-plugin-gradle/3.23.0/spotless-plugin-gradle-3.23.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/diffplug/spotless/spotless-plugin-gradle/3.23.0/spotless-plugin-gradle-3.23.0.jar
/usr/share/java/.m2/repository/com/diffplug/spotless/spotless-plugin-gradle/3.23.0/spotless-plugin-gradle-3.23.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-spotless/LICENSE.txt
/usr/share/package-licenses/mvn-spotless/_ext_eclipse-base_LICENSE.txt
/usr/share/package-licenses/mvn-spotless/_ext_eclipse-cdt_LICENSE.txt
/usr/share/package-licenses/mvn-spotless/_ext_eclipse-groovy_LICENSE.txt
/usr/share/package-licenses/mvn-spotless/_ext_eclipse-jdt_LICENSE.txt
/usr/share/package-licenses/mvn-spotless/_ext_eclipse-wtp_LICENSE.txt
/usr/share/package-licenses/mvn-spotless/lib_src_main_java_com_diffplug_spotless_generic_LicenseHeaderStep.java
/usr/share/package-licenses/mvn-spotless/plugin-maven_src_main_java_com_diffplug_spotless_maven_generic_LicenseHeader.java
/usr/share/package-licenses/mvn-spotless/plugin-maven_src_test_java_com_diffplug_spotless_maven_generic_LicenseHeaderTest.java
/usr/share/package-licenses/mvn-spotless/spotless.license
